php_version: "8.0"
php_packages:
  - php
  - php-cli
  - php-fpm
  - php-mysql
  - php-xml
  - php-mbstring
  - php-curl
  - php-zip
  - php-gd

php_fpm_pool:
  user: "www-data"
  group: "www-data"
  listen: "/run/php/php8.0-fpm.sock"
  listen_mode: "0660"
  pm: "dynamic"
  pm_max_children: "5"
  pm_start_servers: "2"
  pm_min_spare_servers: "1"
  pm_max_spare_servers: "3"